#Settings for the application

# Whether to encrypt private keys
private_key_encryption: true

# Number of threads to use for processing wallets
threads: 1

#BY DEFAULT: [0,0] - all wallets
#Example: [2, 6] will run wallets 2,3,4,5,6
#[4,4] will run only wallet 4
range_wallets_to_run: [0,0]

# Whether to shuffle the list of wallets before processing
shuffle_wallets: true

# Working only if range_wallet_to_run = [0,0] 
# BY DEFAULT: [] - all wallets 
# Example: [1, 3, 8] - will run only 1, 3 and 8 wallets
exact_wallets_to_run: []

# Show wallet address in logs
show_wallet_address_logs: false

#Check for github updates
check_git_updates: true

# the log level for the application. Options: DEBUG, INFO, WARNING, ERROR
log_level : INFO

# Delay before running the new cicle of wallets after it has completed Sprite Types Game actions (1 - 2 hrs default)
# This Setting only for 2 option "Start Complete SpriteTypes games"
random_pause_wallet_after_completion_sprite_types_game:
  min: 3600
  max: 7200

# Delay before running the new cicle of wallets after it has completed all actions(24-25 hrs default)
# This Setting only for 1 option "Run all Activities"
random_pause_wallet_after_all_completion:
  min: 86400
  max: 90000
# Random pause between actions in seconds
random_pause_between_actions:
  min: 30
  max: 120

# Random pause between start wallets in seconds
random_pause_start_wallet:
  min: 0
  max: 60


#Perform automatic replacement from proxy reserve files
auto_replace_proxy: True

# Api Key from https://dash.capmonster.cloud/
capmonster_api_key: ""
#Buy galxe subscription. Need 2$ in Native. Available networks: Arbitrum, Base, Polygon, Bsc
buy_galxe_subscription: True
#Network can use for bridge to Gravity, for Galxe quests. Available: ethereum, arbitrum, base, optimism, ink, mode, bsc, op_bnb, polygon, soneium, lisk, unichain, avalanche, zksync, linea
network_for_bridge: [arbitrum, base, optimism]
#Random diaposon for ETH bridge. (0.1$ - 0.5$ in ETH default)
random_eth_for_bridge:
  min: 0.000025
  max: 0.0001

#Irys Onchain
#Multiple Mint. Minting more > 1 NFT to Wallet
multiple_mint: False
# Random daily play for https://play.irys.xyz/ games
random_irys_games:
  min: 1
  max: 1
